stages:
  - install
  - test
  - deploy

### INSTALL ###
bootstrap:
  stage: install
  cache:
    paths:
      - node_modules/
  artifacts:
    untracked: true
  script:
    - npm install

### TEST ###
lint:standard:
  stage: test
  # runs as soon as bootstrap is finished
  needs:
    - bootstrap
  dependencies:
    - bootstrap
  script:
    - npm run lint:standard

lint:style:
  stage: test
  # runs as soon as bootstrap is finished
  needs:
    - bootstrap
  dependencies:
    - bootstrap
  script:
    - npm run lint:style

lint:typecheck:
  stage: test
  # runs as soon as bootstrap is finished
  needs:
    - bootstrap
  dependencies:
    - bootstrap
  script:
    - npm run lint:typecheck

test:unit:
  stage: test
  # runs as soon as bootstrap is finished
  needs:
    - bootstrap
  dependencies:
    - bootstrap
  script:
    - npm run test
